# common

[default_session]
startup_command = "tmuxp load mysession -a"

[[session]]
name = "VCP Main"
path = "~/code/vcp-web/main"
startup_command = "tmuxp load mysession -a"

[[session]]
name = "VCP Report Generator Main"
path = "~/code/vcp-report-generator/main"

[[session]]
name = "Dotfiles"
path = "~/dotfiles-v4"
